football:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: estudos-dbt-e-bigquery
      dataset: dbt_football
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile: /home/pedromarques/Documentos/Autenticação/BigQuery/estudos-dbt-e-bigquery-390e4a366d25.json